### ISSUE TITLE
Resolve Security Warning for http-server dependency, ecstatic

### ISSUE THREAD

**Issue by douglas-johnson** [thoughtis/prototyping-boilerplate#4]
See: https://github.com/thoughtis/prototyping-boilerplate/network/alert/package-lock.json/ecstatic/open

Try to use NPM audit for fix this warning, and report back if it doesn't work.

**Comment by richdacuban** [comment]
@douglas-johnson found this security report as a result of running an audit:
<img width="753" alt="Screen Shot 2020-04-07 at 10 37 58 AM" src="https://user-images.githubusercontent.com/40250614/78682911-9cea3180-78bc-11ea-84c8-cd4e9e4cd226.png">

`npm audit fix` does not resolve the issue
<img width="542" alt="Screen Shot 2020-04-07 at 10 50 51 AM" src="https://user-images.githubusercontent.com/40250614/78683769-b344bd00-78bd-11ea-954d-fbf73bc8557c.png">

[Here](https://www.npmjs.com/advisories/1179) is the advisory linked in the `npm audit` report. The stated solution is update a dep called `minimist` to at least vers 1.2.3 and we have in our [package lock](https://github.com/thoughtis/prototyping-boilerplate/blob/f1d1a404099aeeffc83fa20da99e6c4ccc4c0d21/package-lock.json#L104) we have vers  1.2.5 installed.

**Comment by douglas-johnson** [comment]
@richdacuban can you look into a replacement for http-server?
